# 🚀 Interactive Jupyter Notebook Tutorial

Welcome to the interactive tutorial! Follow the steps below and learn how to write Python code. You can also use the provided AI Prompts to ask an AI to generate the code for you.

## 1. Get Current Time ⏰
Let's grab the exact current time using Python's built-in library.

In [1]:
import datetime   #we need to find a tool we need from a library. the datatime is a library.
x = datetime.datetime.now()
#the tool "datetime.datetime.now()" provides the current time. we use this tool to get the time info
#and store the value in a variable "x"
print(x)  #now we can print the time

2025-01-11 20:31:51.526293

<div class="alert alert-block alert-success"> 🤖 AI Prompt (Copy this to AI):
Write Python code to import the 'datetime' module, get the current time, store it in a variable named 'x', and print 'x'. </div>

## 2. Print Your Student ID 🎓
Define a variable and print it using string formatting.

In [2]:
StudentID='liujm8' #we give the value "liujm8" to a variable StudentID
print('My Student ID is: %s' %StudentID)

My Student ID is: liujm8

<div class="alert alert-block alert-success"> 🤖 AI Prompt (Copy this to AI):
Write Python code to assign the string 'liujm8' to a variable named 'StudentID', and use string formatting (%s) to print the sentence 'My Student ID is: [StudentID]'. </div>

## 3. Create a Simple Table 📊
Building our very first DataFrame using the Pandas library.
### Please find the documentation of Pandas here:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [3]:
import pandas as pd #now we learn how to store your information in a table using tool "pandas"
mytable=pd.DataFrame(columns=['id','name','time'])
mytable.loc[0]=[StudentID,'LIU Junming',x]
mytable

       id         name                       time
0  liujm8  LIU Junming 2025-01-11 20:31:51.526293

<div class="alert alert-block alert-success"> 🤖 AI Prompt (Copy this to AI):
Using the pandas library, create an empty DataFrame named 'mytable' with columns 'id', 'name', and 'time'. Insert a new row at index 0 with the values: [StudentID, 'LIU Junming', x]. Finally, display the DataFrame. </div>

## 4. Create a Data-rich Table 👯‍♂️
Let's create a more complex DataFrame using a dictionary.

In [4]:
import pandas as pd
import datetime

# Create a DataFrame with some data
data = {
    "id": ["liujm8", "zhangx5", "wangy3", "chenz2"],
    "name": ["LIU Junming", "ZHANG Xi", "WANG Yi", "CHEN Zhi"],
    "grade": [1, 2, 1, 3],
    "score": [87, 92, 78, 88],
    "time": [
        datetime.datetime(2025, 1, 8, 15, 53, 13),
        datetime.datetime(2025, 1, 8, 16, 0, 0),
        datetime.datetime(2025, 1, 8, 16, 5, 0),
        
        datetime.datetime(2025, 1, 8, 16, 10, 0),
    ],
}

df = pd.DataFrame(data)
df

        id         name  grade  score                time
0   liujm8  LIU Junming      1     87 2025-01-08 15:53:13
1  zhangx5     ZHANG Xi      2     92 2025-01-08 16:00:00
2   wangy3      WANG Yi      1     78 2025-01-08 16:05:00
3   chenz2     CHEN Zhi      3     88 2025-01-08 16:10:00

<div class="alert alert-block alert-success"> 🤖 AI Prompt (Copy this to AI):
Write Python code using pandas and datetime to create a DataFrame named 'df'. The DataFrame should be created from a dictionary with the following keys and lists: 'id' ["liujm8", "zhangx5", "wangy3", "chenz2"], 'name' ["LIU Junming", "ZHANG Xi", "WANG Yi", "CHEN Zhi"], 'grade' [1, 2, 1, 3], 'score' [87, 92, 78, 88], and 'time' containing four datetime objects (2025-1-8 15:53:13, 2025-1-8 16:00:00, 2025-1-8 16:05:00, 2025-1-8 16:10:00). Display 'df'. </div>

## 5. Quick Statistics 🧮
Let Pandas calculate our descriptive statistics.

In [5]:
stats = df.describe()
stats

          grade      score
count  4.000000   4.000000
mean   1.750000  86.250000
std    0.957427   5.909033
min    1.000000  78.000000
25%    1.000000  84.750000
50%    1.500000  87.500000
75%    2.250000  89.000000
max    3.000000  92.000000

<div class="alert alert-block alert-success"> 🤖 AI Prompt (Copy this to AI):Write Python code to generate descriptive statistics for the DataFrame 'df' using the .describe() method, assign the result to a variable 'stats', and display it. </div>

## 6. Data Categorization 🏆
Use custom functions and apply them to the DataFrame.

In [6]:
def grade_category(score):
    if score >= 90:
        return "Excellent"
    elif score >= 80:
        return "Good"
    elif score >= 60:
        return "Pass"
    else:
        return "Fail"

df["category"] = df["score"].apply(grade_category)
df

        id         name  grade  score                time   category
0   liujm8  LIU Junming      1     87 2025-01-08 15:53:13       Good
1  zhangx5     ZHANG Xi      2     92 2025-01-08 16:00:00  Excellent
2   wangy3      WANG Yi      1     78 2025-01-08 16:05:00       Pass
3   chenz2     CHEN Zhi      3     88 2025-01-08 16:10:00       Good

<div class="alert alert-block alert-success"> 🤖 AI Prompt (Copy this to AI):
Write a Python function named 'grade_category' that takes a 'score' as input. It should return "Excellent" if score >= 90, "Good" if >= 80, "Pass" if >= 60, and "Fail" otherwise. Use the pandas .apply() method to apply this function to the 'score' column of DataFrame 'df' and store the results in a new column called 'category'. Display 'df'. </div>

## 7. Numpy Matrix Operations 🕶️
Doing standard matrix operations using Numpy.

In [7]:
import numpy as np

# Convert "score" and "grade" columns into a numpy matrix
matrix = df[["score", "grade"]].to_numpy()
print("Original Matrix:")
print(matrix)

# Transpose
transpose = matrix.T
print("\nTransposed Matrix:")
print(transpose)

# Matrix multiplication
result = np.dot(matrix, transpose)
print("\nMatrix Multiplication Result:")
print(result)

# Calculate all scores and grades
sum_matrix = np.sum(matrix, axis=0)  # Sum along columns
print("\nSum of Scores and Grades:")
print(sum_matrix)

Original Matrix:
[[87  1]
 [92  2]
 [78  1]
 [88  3]]

Transposed Matrix:
[[87 92 78 88]
 [ 1  2  1  3]]

Matrix Multiplication Result:
[[7570 8006 6787 7659]
 [8006 8468 7178 8102]
 [6787 7178 6085 6867]
 [7659 8102 6867 7753]]

Sum of Scores and Grades:
[345   7]

<div class="alert alert-block alert-success"> 🤖 AI Prompt (Copy this to AI):
Write Python code using numpy to perform the following operations: 1. Extract the "score" and "grade" columns from DataFrame 'df' and convert them to a numpy array named 'matrix'. Print it. 2. Get the transpose of 'matrix', store it in 'transpose', and print it. 3. Calculate the dot product of 'matrix' and 'transpose', store it in 'result', and print it. 4. Calculate the sum of 'matrix' along the columns (axis=0), store it in 'sum_matrix', and print it. </div>

## Tutorial 1:
### Please complete the following questions using this jupyter notebook, SAVE it as HTML and upload to canvas.

#### (1) (20 points) use the jupyter notebook to print the following information:
#### Your student ID, your name, and your current time.
#### (2) (20 points) put the information above into a pandas dataframe (the table in step 3)
#### (3) (30 points) after a few seconds, add the second row of your id, name, time, expected scores
#### (4) (30 points) Perform matrix operations with numpy:
- Convert the score and grade columns into a numpy matrix.
- Print the matrix and its transpose.
- Calculate and print the sum of all scores.